"""Initial migration.

Revision ID: 6fcd90451eda
Revises: 
Create Date: 2023-07-28 03:43:53.418378

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6fcd90451eda"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.String(length=128), nullable=True),
        sa.Column("operator", sa.String(length=128), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_result")
    # ### end Alembic commands ###
